### ISSUE TITLE
Can't find Mawaqit Skill in Alexa

### ISSUE THREAD

**Issue by jaxfellow** [mawaqit/alexa#1]
Hello team,
I was trying to add Mawaqit to my Alexa skills but I couldn't find it. I found out that it has been almost 3 years since the last update on this repo so I was wondering if its still active.
Thank you

**Comment by bsene** [comment]
@jaxfellow  I'm currently working professionally on Alexa stuff.
Maybe I can handle this

**Comment by F1o0T** [comment]
@bsene  Alsalam Alikom, I live in Hamburg, I am currently trying to find the Alexa skill, but it is not there. May I ask if you have any updates?

**Comment by bsene** [comment]
@F1o0T  I finally do not have the time to work on it 😅
Now I see @ijaz26 adding some improvements we might ask him about a possible release

**Comment by ijaz26** [comment]
Australia   -  Link to Skill Store: [](https://www.amazon.com.au/dp/B0DL2558YY)
Canada  -  Link to Skill Store: [](https://www.amazon.ca/dp/B0DL2558YY)
France   -   Link to Skill Store: [](https://www.amazon.fr/dp/B0DL2558YY)
India  -   Link to Skill Store: [](https://www.amazon.in/dp/B0DL2558YY)
United Kingdom  -   Link to Skill Store: [](https://www.amazon.co.uk/dp/B0DL2558YY)
United States   -  Link to Skill Store: [](https://www.amazon.com/dp/B0DL2558YY)

**Comment by ijaz26** [comment]
MAWAQIT Alexa Skill has been released in following countries. 
Link to Skill Store: [Australia](https://www.amazon.com.au/dp/B0DL2558YY)
Link to Skill Store: [Canada](https://www.amazon.ca/dp/B0DL2558YY)
Link to Skill Store: [France](https://www.amazon.fr/dp/B0DL2558YY)
Link to Skill Store: [India](https://www.amazon.in/dp/B0DL2558YY)
Link to Skill Store: [United Kingdom](https://www.amazon.co.uk/dp/B0DL2558YY)
Link to Skill Store: [United States](https://www.amazon.com/dp/B0DL2558YY)

**Comment by F1o0T** [comment]
Thanks a lot, will it also work in Germany? @ijaz26

**Comment by ijaz26** [comment]
> Thanks a lot, will it also work in Germany? @ijaz26

@F1o0T ,
Currently, the skill is not available in Germany. InshaAllah, we are actively working on expanding its availability to other countries, including Germany.

**Comment by F1o0T** [comment]
Great, thanks a lot.
